sudo: false
language: java
jdk:
- oraclejdk8
before_script:
- npm install -g grunt-cli
- npm install -g bower
- npm install -g tsd
script: ./gradlew test
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU-API-KEY
  app: chatty42
  on:
    repo: toedter/chatty
