sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install -g tsd
  - curl -O https://downloads.giantswarm.io/swarm/clients/0.24.1/swarm-0.24.1-linux-amd64.tar.gz
  - sudo tar xzf swarm-0.24.1-linux-amd64.tar.gz -C /usr/local/bin

script:
  - ./gradlew gruntDist
  - ./gradlew build
  - cd subprojects/com.toedter.chatty.server.boot
  - ../../gradlew dockerfile
  - cd build
  - docker build -t kaitoedter/chatty .
  - docker login --email="$DOCKER_EMAIL" --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD"
  - docker push kaitoedter/chatty
  - cd ../../..
  - swarm login $SWARM_USER -p $SWARM_PASSWORD
  - sudo docker tag -f kaitoedter/chatty registry.giantswarm.io/toedter/chatty-boot
  - docker push registry.giantswarm.io/toedter/chatty-boot
  - swarm update chatty/chatty-server

deploy:
  provider: heroku
  api_key:
    secure: T+25rIkOT1erceI6nJ7Y1hYASsnTuMDqEzLcJHNbmuaDXiaiyVs9RUnmWLCpEHz4bzvwlcojYWis2sFD0/Iu7ajZOwW9PtCH4uCE0ZwkHS/NlxPYbKDEpGW+BSDSildxdFU/9pGQgKy+wt5w6bslo8j17m5CK410htt6sAiS+tE=
  app: chatty42
  on:
    repo: toedter/chatty
