sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install -g tsd
#  - sudo rm /usr/local/bin/docker-compose
#  - curl -L https://github.com/docker/compose/releases/download/1.5.1/docker-compose-`uname -s`-`uname -m` > docker-compose
#  - chmod +x docker-compose
#  - sudo mv docker-compose /usr/local/bin

script:
  - ./gradlew gruntDist
  - ./gradlew build
#  - docker-compose build chatty-boot
#  - docker tag chatty_chatty-boot kaitoedter/chatty
#  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
#  - docker push kaitoedter/chatty

deploy:
  provider: heroku
  api_key:
    secure: T+25rIkOT1erceI6nJ7Y1hYASsnTuMDqEzLcJHNbmuaDXiaiyVs9RUnmWLCpEHz4bzvwlcojYWis2sFD0/Iu7ajZOwW9PtCH4uCE0ZwkHS/NlxPYbKDEpGW+BSDSildxdFU/9pGQgKy+wt5w6bslo8j17m5CK410htt6sAiS+tE=
  app: chatty42
  on:
    repo: toedter/chatty
